### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Arshiya051** [zitengzela/LegionCore-7.3.5V2#2]
Problem logging in to the account.
Please check the photos and tell me where is the problem?
https://s6.uupload.ir/files/1_r0g1.png
https://s6.uupload.ir/files/2_ujrt.png
https://s6.uupload.ir/files/3_455j.png
https://s6.uupload.ir/files/4_y5ph.png
https://s6.uupload.ir/files/5_w85b.png
@SargeroDeV 
@Devir7 
@zitengzela

**Comment by yboku** [comment]
Wow.exe patched?
I used this client version 7.3.5_26654.

**Comment by Arshiya051** [comment]
No, I use another server's client. For Legion, the server is ok and enters the game. Now, if you think there is a problem with the patching of the client, and if you have a patched client yourself, please send it so I can test it. Thankful
@yboku

**Comment by yboku** [comment]
Try searching other Legion projects for a working connection_patcher.exe.
I don't have any links left, I found this a long time ago.

**Comment by Arshiya051** [comment]
If possible, upload and send the WTF folder and the client files inside the main folder so that I can test it.
@yboku

**Comment by Arshiya051** [comment]
Can you send me your auth database? And what command do you use to create an account?
@yboku

**Comment by yboku** [comment]
incorrectly created account in photo 1.
Bnetaccount create nik@nik password
Try this client. I haven't tested it!
https://drive.google.com/drive/folders/16X6lQVF5MaQBph8_6OeJTmfCvb7GaNZM

**Comment by Arshiya051** [comment]
I have a full client. I tested it on other sources, it is correct. I don't have connection_patcher.exe to build a dedicated client. That's why I said if you made a client for yourself, let me test it. I just wanted wow64.exe.

**Comment by Arshiya051** [comment]
My problem is solved. The problem was creating an account. I used the wrong command.
@yboku 
ty.
